# Generated by Django 3.0.8 on 2020-07-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_url', models.CharField(max_length=200, verbose_name='Gif url')),
                ('votes', models.IntegerField(verbose_name='Votos')),
            ],
        ),
    ]
